public enum PLAYER { P1, P2 };
public enum STATES { CHOOSE_OWN_CARD, CHOOSE_ENEMY_CARD, BLOCK_STAT, CHOOSE_ENGAGEMENT, CHOOSE_STATS, NONE }
public enum EENGAGMENT { SMALL, MEDIM, HUGE, DIFFERENCE_1, DIFFERENCE_2, DIFFERENCE_3 }
public enum POSITION_NAME { RF, LF, RM, CRM, CLM, LM, RD, CRD, CLD, LD, GK, CF, CM, CD }
public enum POS_LINE { ATTACK, HELP, DEFENDER, GOALKEEPER }
public enum POS_COLUMN { RIGHT = 0, CENTER_RIGHT = 1, CENTER = 1, CENTER_LEFT = 1, LEFT = 2, GOAL_KEEPER = 3 }
public enum FORMATION { F442, F433, F343, NONE }